"""initial migration

Revision ID: a8e9463cdd29
Revises:
Create Date: 2026-05-22 21:56:20.648749

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy as pgv  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "a8e9463cdd29"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcripttheme",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "transcript",
        sa.Column("transcript_id", sa.Integer(), nullable=False),
        sa.Column("call_entity_id", sa.Integer(), nullable=False),
        sa.Column("theme_id", sa.Integer(), nullable=True),
        sa.Column("clear_transcript", sa.String(), nullable=False),
        sa.Column("embedding", pgv.vector.VECTOR(dim=768), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["transcripttheme.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transcript_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transcript")
    op.drop_table("transcripttheme")
    # ### end Alembic commands ###
